# Generated by Django 6.0 on 2025-12-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('create_event', 'Can create event'), ('update_event', 'Can update event')]},
        ),
    ]
