# Generated by Django 6.0 on 2025-12-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('create_event', 'Can create event'), ('update_event', 'Can update event'), ('assign_event_coordinator', 'Can change event coordinator for any event')]},
        ),
    ]
