# Generated by Django 6.0 on 2026-01-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('photo_upload', 'Photo Upload'), ('bulk_upload', 'Bulk Upload'), ('comment', 'Comment'), ('reply', 'Reply'), ('photo_like', 'Photo Like'), ('tagged', 'Tagged')], max_length=50),
        ),
    ]
