# Generated by Django 6.0 on 2025-12-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
