# Generated by Django 6.0 on 2025-12-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'permissions': [('upload_photo', 'Can upload photo'), ('delete_any_photo', 'Can delete any photo')]},
        ),
    ]
