# Generated by Django 6.0 on 2025-12-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photosharelink'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photoversion',
            unique_together={('photo', 'resolution', 'is_watermarked')},
        ),
    ]
