# Generated by Django 6.0 on 2026-01-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photoview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototag',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_tags', to='photos.photo'),
        ),
    ]
