# Generated by Django 6.0 on 2026-01-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_phototag_photo'),
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedby',
            name='tagged_by',
        ),
        migrations.AlterField(
            model_name='taggedby',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='photos.photo'),
        ),
    ]
