# Generated by Django 6.0 on 2026-01-14 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_taggedby_tagged_by_alter_taggedby_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggedby',
            name='tagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
