# Generated by Django 6.0 on 2026-01-14 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_taggedby_tagged_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedby',
            name='tagged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
